/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package basiclibrary;

import org.junit.Test;
import static org.junit.Assert.*;

public class LibraryTest {
    @Test public void testSomeLibraryMethod() {
        Library classUnderTest = new Library();
        assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
    }

    @Test public void testRoll() {
        Library libraryForTesting = new Library();
        int input = 4;
        int[] expected = new int[input];
        int expectedLength = expected.length;
        assertEquals("rolling die should result in and array of N numbers", expectedLength, ArrayLists.roll(input).length);
    }

    @Test public void testContainsDuplicates() {
        Library libraryForTesting = new Library();
        int[] input = {1, 2, 2, 3, 4};
        assertTrue("should return 'true'", ArrayLists.containsDuplicates(input));
    }

    @Test public void testCalculateAverage() {
        Library libraryForTesting = new Library();
        int[] input = new int[] {1, 2, 3};
        int expected = 2;
        assertEquals("should return the average of the given array of integers", expected, ArrayLists.calculateAverage(input));
    }

    @Test public void testArrOfArr() {
        int[][] input = {
                {66, 64, 58, 65, 71, 57, 60},
                {57, 65, 65, 70, 72, 65, 51},
                {55, 54, 60, 53, 59, 57, 61},
                {65, 56, 55, 52, 55, 62, 57}
        };
        int[] expected = input[2];
        assertEquals("should return array with the lowest average", expected, ArrayLists.arrOfArrAverage(input));
    }

    @Test public void testMaps() {
        int [][] input = {
                {66, 64, 58, 65, 71, 57, 60},
                {57, 65, 65, 70, 72, 65, 51},
                {55, 54, 60, 53, 59, 57, 61},
                {65, 56, 55, 52, 55, 62, 57}
        };
        String expected = "High: 72\n" +
                "Low: 51\n" +
                "Never saw temperature: 63\n" +
                "Never saw temperature: 67\n" +
                "Never saw temperature: 68\n" +
                "Never saw temperature: 69";
        assertEquals("should return a string", expected, Tally.maps(input));
    }

    @Test public void testTally() {

    }
}
